source 'https://github.com/PMComponent/PMSpace.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '10.0'

target 'PMSpecialKit_Example' do
  pod 'PMSpecialKit', :path => '../'

  target 'PMSpecialKit_Tests' do
    inherit! :search_paths

    
  end
end
